file = open('exception.py', 'r')
print(file.read())